[package]
name = "peck-lib"
version = "1.0.0"
edition = "2021"
description = "A set of library and type functions."
license = "MIT"
repository = "https://github.com/alexipeck/peck-lib/"
categories = []
authors = ["Alexi Peck"]
exclude = ["/target"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
