[package]
name = "peck-lib"
version = "1.1.1"
description = "A library of functions, traits, serde implementations for error handling, logging, hashing and datetime's."
license = "MIT"
edition = "2021"
repository = "https://github.com/alexipeck/peck-lib/"
categories = []
authors = ["Alexi Peck"]
exclude = ["/target", "main.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.194", features = ["derive"] }
chrono = "0.4.31"
tracing-subscriber = { version = "0.3.18" }
tracing = "0.1.40"
reqwest = {version = "0.11.23", features = ["json"]}
thiserror = "1.0.56"
blake3 = "1.5.0"
tokio = "1.35.1"